deeson_warden:
    resource: "@DeesonWardenBundle/Resources/config/routing.yml"
    prefix:   /

generator_warden:
    resource: "@MUYMGeneratorBundle/Resources/config/routing.yml"
    prefix:   /

deeson_warden_third_party_library:
    resource: "@DeesonWardenThirdPartyLibraryBundle/Resources/config/routing.yml"
    prefix:   /
