_secured:
    resource: "@DeesonWardenBundle/Controller/SecuredController.php"
    type:     annotation

_unauthorised:
    path: /unauthorised
    defaults: { _controller: DeesonWardenBundle:Dashboard:unauthorised }

_dashboard:
    path:  /generator
    defaults: { _controller: MUYMGeneratorBundle:Generator:generatorIndex }

#generator_list:
#    path:    /sites
#    defaults: { _controller: DeesonWardenBundle:Sites:index }

#module_add:
#    path:    /sites/add
#    defaults: { _controller: DeesonWardenBundle:Sites:add }

#module_show:
#    path:    /sites/{id}
#    defaults: { _controller: DeesonWardenBundle:Sites:show }

#module_edit:
#    path:    /sites/{id}/edit
#    defaults: { _controller: DeesonWardenBundle:Sites:edit }

#module_delete:
#    path:    /sites/{id}/delete
#    defaults: { _controller: DeesonWardenBundle:Sites:delete }

#module_deploy:
#    path:    /sites/{id}/refresh
#    defaults: { _controller: DeesonWardenBundle:Sites:refresh }